// <copyright file="GlobalSuppressions.cs" company="VSEC">
// Copyright (c) VSEC. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.Models.Contract.#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.Models.ContractHistory.#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.Models.Contract.#ctor(System.Int32,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.Models.ContractHistory.#ctor(System.Int32,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.Models.Contract.#ctor(System.Guid,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter must not span multiple lines", Justification = "Pending", Scope = "member", Target = "~M:HMKT.Model.DbInitialize.DataSeeder.LanguageSeeding(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
